### ISSUE TITLE
Link to App Store on Product Hunt

### ISSUE THREAD

**Issue by AlexPoulsen** [datwheat/Startr#1]
Is the iOS version on the App Store? If it is, because I can't find it, link it on the product hunt page.

**Comment by FiberJW** [comment]
Hello, the app is not on the app store, only on Google Play

**Comment by brentvatne** [comment]
Heya @AlexPoulsen - you can try it out here on Exponent: https://getexponent.com/@community/startr -- I forked the project, got it running on iOS, and published it there for the convenience of people who want to give it a try @datwheat :)

**Comment by FiberJW** [comment]
That's awesome thanks @brentvatne !

**Comment by brentvatne** [comment]
Fork here: https://github.com/brentvatne/Startr

**Comment by FiberJW** [comment]
@brentvatne could you remove the `marginBottom: 50,` in the nested view in your fork?

**Comment by FiberJW** [comment]
Since the adUnit isn't there anymore the view doesn't need to compensate for that used space. thanks!
